### PR TITLE
Changing variable name T to TImer or Temperature in both SANA.hpp and…

### PR DESCRIPTION
**Pull request by haoanwang0829**
… SANA.cpp

### CODE REVIEW

**Comment by haoanwang0829** [comment]
Hi professor, I am Peter Wang. I am trying to send a pull request, but it seems that it said "review required" and "merging is blocked". I am not sure you receive this pull request.

**Comment by waynebhayes** [comment]
Yes I saw it, I'll take a look at it when I get a moment. All pull requests
must be reviewed before being accepted---that's the point of pull requests.

-- 
Wayne Hayes, Ph.D.
Director, UCI-SDSU Joint Ph.D. Program in Computational Science (UCI side)
Associate Professor, Computer Science, University of California, Irvine
President Trump is a self-absorbed, self-serving, habitual liar. The former
two are opinion; the latter is fact. Examples (1)
http://foreignpolicy.com/2017/08/18/trumps-lies-about-james-comey-keep-unraveling
. (2) https://www.theguardian.com/us-news/trump-administration

**Comment by waynebhayes** [comment]
PS: did you do a "git pull" this morning and then "make" to ensure
everything works with the latest changes?

**Comment by haoanwang0829** [comment]
I didn't do git pull. But I deleted all the old files and started by git
clone. So all the changes were made on latest version. I did not run the
code to check everything works fine. I will check after lunch.

Professor Wayne B. Hayes, UC Irvine <notifications@github.com>于2018年7月17日
周二13:37写道：

**Review by waynebhayes — APPROVED** [review]

**Pull request merged**
